/*
	CREAR DATABASE

*/

CREATE DATABASE ejemploEgg;

/*
	AGREGAR FILAS CON VALORES
*/
CREATE TABLE `ejemploEgg`.`new_table` (
  `id_table` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `edad` INT NULL,
  PRIMARY KEY (`id_table`));


SELECT * FROM new_table;

INSERT INTO new_table (ID_TABLE,NOMBRE,APELLIDO,EDAD) VALUES(1,'bruno','zenobio',25);
INSERT INTO new_table (ID_TABLE,NOMBRE,APELLIDO,EDAD) VALUES(2,'angela','rivero',25);
INSERT INTO new_table (ID_TABLE,NOMBRE,APELLIDO,EDAD) VALUES(3,'carlos','pelir',10);
INSERT INTO new_table (ID_TABLE,NOMBRE,APELLIDO,EDAD) VALUES(4,'gonzalo','perez',55);
INSERT INTO new_table (ID_TABLE,NOMBRE,APELLIDO,EDAD) VALUES(5,'alfredo','bañero',32);


/*
MODIFICANDO VALORES DE LA TABLA
*/


SELECT * FROM new_table;

UPDATE new_table
	SET EDAD = 30
WHERE ID_TABLE = 4;

/*
ELIMINAR VALORES
*/
SELECT * FROM new_table;
DELETE 
	FROM new_table
WHERE id_table = 3;



/*
	SLECT Y FROM WHERE MAS EN PROFUNDIDAD

*/

/*
	SELECCIONAR LA COLUMNA SOLO CON UN CODIGO ESPECIFICO (O CONDICION)
*/

SELECT * FROM new_table WHERE ID_TABLE = 4;


/*
	PEDIR CAMPO EN PARTICULAR Y ADEMAS PEDIR UN VALOR DE FILA, SI QUIERO TODOS LOS VALORES DE UNA COLUMNA NO USO EL WHERE
    

    */
    
SELECT NOMBRE,APELLIDO FROM new_table WHERE ID_TABLE =  2;
SELECT * FROM new_table WHERE edad > 30;
SELECT * FROM new_table WHERE nombre = 'angela';
SELECT * FROM new_table WHERE edad = 25 AND nombre = 'bruno';

/*
	FUNCIONES DENTRO DE UN SLECT
*/

SELECT COUNT(*) FROM new_table;/*CANTIDAD DE REGISTROS(FILAS)*/
SELECT COUNT(*) FROM new_table WHERE edad = 25;/*CANTIDAD DE REGISTROS(FILAS) PERO SOLO CON LA COLUMNA EDAD = 25*/
SELECT MAX(ID_TABLE) FROM new_table;/*MAX()ATRIBUTO) TRAE EL ATRIBUTO MAXIMO*/
 SELECT MAX(edad) FROM new_table;
  SELECT MIN(edad) FROM new_table;
/*
	SENTENCIA IN PARA TRAER MAS DE UN VALOR SEGUN CONDICION
*/

SELECT * FROM new_table WHERE id_table IN (1,4);/*ME DEVUELVE LAS FILAS  DONDE EL ID ES 1 y 4*/

/*FUNCION LIKE WHERE ATRIBUTO LIKE tenga el contenido dicho*/

SELECT * FROM new_table WHERE nombre LIKE '%ru%';/*EL ATIRBUTO NOMBRE CONTENGA LA CADENA ru SI QUIERO QUE CO
COMIENCE CON lA CADENA DEBO QUITAR EL % DEL INICIO Y PARA EL FINAL AL REVES*/

/*
	BETWEEN EL VALOR EStE ENtrE LOS VALORES ESPECIFICADOS
*/

SELECT * FROM new_table WHERE edad BETWEEN 20 AND 40;
