#Ejercicio 2 extra mysql
select codigo_oficina,ciudad from oficina;
select o.ciudad,o.telefono from oficina o where o.pais = "España";
select nombre,apellido1,apellido2 from empleado where codigo_jefe = 7;
select puesto,nombre,apellido1,apellido2 from empleado where codigo_jefe is null;
select nombre,apellido1,apellido2 from empleado where not puesto = 'Representante Ventas';
select nombre_cliente from cliente where pais = 'spain';
select distinct estado from pedido;
select distinct codigo_cliente from pago where year(fecha_pago) = 2008;
select distinct codigo_cliente from pago where date_format(fecha_pago,"%Y") = 2008; 
select distinct codigo_cliente from pago where fecha_pago like '2008%';
select codigo_pedido,codigo_cliente,fecha_esperada,fecha_entrega from pedido where datediff(fecha_entrega,fecha_esperada)>0;
select codigo_pedido,codigo_cliente,fecha_esperada,fecha_entrega from pedido where datediff(fecha_esperada,fecha_entrega)>=2;
select codigo_pedido,codigo_cliente,fecha_esperada,fecha_entrega from pedido where adddate(fecha_entrega,interval 2 day) = fecha_esperada;
select * from pedido where year(fecha_pedido) = 2009 and estado = 'Rechazado';
select * from pedido where month(fecha_entrega) = 1 ;
select * from pago where year(fecha_pago) = 2008 and forma_pago = 'PayPal' ;
select distinct forma_pago from pago;
select * from producto where gama = 'Ornamentales' and cantidad_en_stock = 100 order by precio_venta desc;
select * from cliente where ciudad = 'Madrid' and codigo_empleado_rep_ventas in (11,30);
select nombre_cliente,nombre as Nombre_Rep_Ventas,apellido1,apellido2 from cliente inner join empleado on cliente.codigo_empleado_rep_ventas = empleado.codigo_empleado;
select nombre_cliente,nombre as Nombre_Rep_Ventas from cliente inner join empleado on codigo_empleado_rep_ventas = codigo_empleado where codigo_cliente in (select codigo_cliente from pago);
select nombre_cliente,nombre as Nombre_Rep_Ventas from cliente inner join empleado on codigo_empleado_rep_ventas = codigo_empleado where codigo_cliente not in (select codigo_cliente from pago);
select nombre_cliente,nombre as Nombre_Rep_Ventas,oficina.ciudad from cliente inner join empleado on codigo_empleado_rep_ventas = codigo_empleado inner join oficina on empleado.codigo_oficina = oficina.codigo_oficina where codigo_cliente  in (select codigo_cliente from pago);
select nombre_cliente,nombre as Nombre_Rep_Ventas,oficina.ciudad from cliente inner join empleado on codigo_empleado_rep_ventas = codigo_empleado inner join oficina on empleado.codigo_oficina = oficina.codigo_oficina where codigo_cliente not in (select codigo_cliente from pago);
select o.linea_direccion1,o.linea_direccion2 from oficina  o inner join empleado e on o.codigo_oficina = e.codigo_oficina inner join cliente c on e.codigo_empleado = c.codigo_empleado_rep_ventas where c.ciudad = 'Fuenlabrada';
select c.nombre_cliente,e.nombre as Nombre_Rep_Ventas,o.ciudad as Ciudad_Oficina from cliente c inner join empleado e on c.codigo_empleado_rep_ventas = e.codigo_empleado inner join oficina o on e.codigo_oficina = o.codigo_oficina;
select e.nombre as Nombre_empleado,e2.nombre as Nombre_jefe from empleado e inner join empleado e2 on e.codigo_jefe = e2.codigo_empleado;
select c.nombre_cliente from cliente c inner join pedido p on c.codigo_cliente = p.codigo_cliente where estado = 'Pendiente';
select c.nombre_cliente from cliente c left join pago p on c.codigo_cliente = p.codigo_cliente where p.codigo_cliente is null;
select c.nombre_cliente from cliente c left join pedido p on c.codigo_cliente = p.codigo_cliente where p.codigo_cliente is null;
select c.nombre_cliente from cliente c left join pedido p on c.codigo_cliente = p.codigo_cliente  inner join pago pa on c.codigo_cliente = pa.codigo_cliente where p.codigo_cliente is null or pa.codigo_cliente is null;
select e.nombre from oficina o right join empleado e on e.codigo_oficina = o.codigo_oficina where e.codigo_oficina is null;
select e.nombre from empleado e left join cliente c on e.codigo_empleado=c.codigo_empleado_rep_ventas where c.codigo_empleado_rep_ventas is null;
select e.nombre from oficina o right join empleado e on e.codigo_oficina = o.codigo_oficina left join cliente c on e.codigo_empleado = c.codigo_empleado_rep_ventas where e.codigo_oficina is null or c.codigo_empleado_rep_ventas is null;
select p.nombre,p.codigo_producto from producto p left join detalle_pedido de on p.codigo_producto = de.codigo_producto where de.codigo_pedido is null;
select o.codigo_oficina,o.ciudad from oficina o left join empleado e on o.codigo_oficina = e.codigo_oficina where e.codigo_empleado not in(select c.codigo_empleado_rep_ventas from cliente c left join pedido p on c.codigo_cliente = p.codigo_cliente left join detalle_pedido de on p.codigo_pedido = de.codigo_pedido left join producto pr on de.codigo_producto = pr.codigo_producto where pr.gama ='Frutales');
select distinct c.nombre_cliente from cliente c inner join pedido pe on c.codigo_cliente = pe.codigo_cliente left join pago p on p.codigo_cliente = c.codigo_cliente where p.codigo_cliente is null;
select e.nombre,e2.nombre as Nombre_Jefe from empleado e inner join empleado e2 on e.codigo_jefe = e2.codigo_jefe left join cliente c on e.codigo_empleado = c.codigo_empleado_rep_ventas where c.codigo_empleado_rep_ventas is null;
select count(nombre) as Cantidad_empleados from empleado;
select count(nombre_cliente),pais from cliente group by pais;
select avg(total) from pago where year(fecha_pago) = 2009;
select count(codigo_pedido) as Pedidos,estado from pedido group by estado  order by count(codigo_pedido) DESC;
select max(precio_venta),min(precio_venta) from producto;
select count(codigo_cliente) as Numero_clientes from cliente;
select count(codigo_cliente) as Numero_clientes from cliente where ciudad='Madrid';
select count(codigo_cliente) as Numero_clientes,ciudad from cliente where ciudad like 'M%' group by ciudad;
select e.nombre,count(c.nombre_cliente) from empleado e inner join cliente c on e.codigo_empleado = c.codigo_empleado_rep_ventas group by c.codigo_empleado_rep_ventas;
select count(c.nombre_cliente) Numero_clientes from cliente c left join empleado e on e.codigo_empleado = c.codigo_empleado_rep_ventas where e.codigo_empleado is null;
select nombre_cliente,max(fecha_pago),min(fecha_pago) from cliente c inner join pago p on c.codigo_cliente = p.codigo_cliente group by p.codigo_cliente;
select count(distinct p.codigo_producto) as Numero_productos from producto p inner join detalle_pedido de on p.codigo_producto = de.codigo_producto inner join pedido pe on de.codigo_pedido = pe.codigo_pedido group by pe.codigo_pedido;
select pe.codigo_pedido,sum(p.precio_venta) as Numero_productos from producto p inner join detalle_pedido de on p.codigo_producto = de.codigo_producto inner join pedido pe on de.codigo_pedido = pe.codigo_pedido group by pe.codigo_pedido;
select p.nombre,sum(cantidad) from producto p inner join detalle_pedido de on p.codigo_producto = de.codigo_producto group by p.codigo_producto order by sum(cantidad) DESC limit 20;
select sum(cantidad) * sum(de.precio_unidad) as Base_imponible,sum(cantidad) * sum(de.precio_unidad) * 0.21 as IVA,sum(cantidad) * sum(de.precio_unidad) * (1 +    0.21) as Total  from detalle_pedido de;
select sum(cantidad) * sum(de.precio_unidad) as Base_imponible,sum(cantidad) * sum(de.precio_unidad) * 0.21 as IVA,sum(cantidad) * sum(de.precio_unidad) * (1 +    0.21) as Total  from detalle_pedido de  group by de.codigo_producto;
select de.codigo_producto,sum(cantidad) * sum(de.precio_unidad) as Base_imponible,sum(cantidad) * sum(de.precio_unidad) * 0.21 as IVA,sum(cantidad) * sum(de.precio_unidad) * (1 +    0.21) as Total  from detalle_pedido de  where de.codigo_producto like 'OR%'  group by de.codigo_producto;
select de.codigo_producto,p.nombre,sum(de.cantidad),sum(de.cantidad)*sum(precio_unidad) as Total_facturado,sum(de.cantidad)*sum(precio_unidad)*1.21 as Total_facturado_iva  from detalle_pedido de inner join producto p on de.codigo_producto=p.codigo_producto  group by de.codigo_producto having sum(de.cantidad)*sum(precio_unidad)>3000 ;
select codigo_cliente,nombre_cliente from cliente where limite_credito = (select max(limite_credito) from cliente);
select codigo_producto,nombre from producto where precio_venta = (select max(precio_venta) from producto);
select nombre from producto where codigo_producto = (select codigo_producto from detalle_pedido group by codigo_producto order by sum(cantidad) DESC limit 1);
select codigo_cliente,nombre_cliente from cliente where limite_credito >  (select sum(total) from pago where pago.codigo_cliente = cliente.codigo_cliente group by codigo_cliente );
select codigo_producto,nombre,cantidad_en_stock from producto where cantidad_en_stock = (select max(cantidad_en_stock) from producto);
select codigo_producto,nombre,cantidad_en_stock from producto where cantidad_en_stock = (select min(cantidad_en_stock) from producto);
select nombre,apellido1,apellido2,email from empleado where codigo_empleado = (select codigo_empleado_rep_ventas from cliente where nombre_cliente = 'Alberto Soria');
select nombre_cliente from cliente where limite_credito = any (select max(limite_credito) from cliente);
select codigo_producto,nombre from producto where precio_venta = any (select max(precio_venta) from producto);
select codigo_producto,nombre from producto where cantidad_en_stock = any (select min(cantidad_en_stock) from producto);
select nombre,apellido1,puesto from empleado  where codigo_empleado not in (select codigo_empleado_rep_ventas from cliente);
select codigo_cliente,nombre_Cliente from cliente where codigo_cliente not in (select codigo_cliente from pago);
select codigo_cliente,nombre_Cliente from cliente where codigo_cliente  in (select codigo_cliente from pago);
select codigo_producto,nombre from producto where codigo_producto not in (select codigo_producto from detalle_pedido);
select codigo_empleado,nombre,apellido1,apellido2,puesto,o.telefono from empleado inner join oficina o on empleado.codigo_oficina = o.codigo_oficina where empleado.codigo_empleado not in (select codigo_empleado_rep_ventas from cliente);
select codigo_cliente,nombre_cliente from cliente where  not exists (select codigo_cliente from pago where cliente.codigo_cliente = pago.codigo_cliente);
select codigo_cliente,nombre_cliente from cliente where   exists (select codigo_cliente from pago where cliente.codigo_cliente = pago.codigo_cliente);
select codigo_producto,nombre from producto where not exists (select codigo_producto from detalle_pedido where producto.codigo_producto = detalle_pedido.codigo_producto);
select codigo_producto,nombre from producto where exists (select codigo_producto from detalle_pedido where producto.codigo_producto = detalle_pedido.codigo_producto);


